import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'
import { describe, expect, it } from 'vitest'

// The committed types are the contract's types: `npm run generate:api` must have been run after
// every change to web-app/backend/openapi.yaml (the backend tests the yaml the same way).
// The Compose service mounts the yaml at OPENAPI_SPEC; outside Compose it is a sibling folder.
const spec = resolve(process.env.OPENAPI_SPEC ?? '../backend/openapi.yaml')
const HEADER = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`

describe('src/api/generated/schema.d.ts', () => {
  it('equals a fresh generation from openapi.yaml', async () => {
    const fresh = HEADER + astToString(await openapiTS(new URL(`file://${spec}`)))
    const committed = readFileSync(resolve('src/api/generated/schema.d.ts'), 'utf8')
    expect(committed).toBe(fresh)
  })
})
