# Generated by Django 5.2.17 on 2026-10-06 09:37

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    # search_vector is a STORED generated column built with GeneratedField(SearchVector(...)).
    # It compiles to to_tsvector('simple'::regconfig, coalesce(title,'') || ' ' ||
    # coalesce(left(body,100000),'') || ' ' || coalesce(replace(path,'/',' '),'')): the
    # 2-argument (immutable) form, with replace() splitting folder names into tokens and
    # left() keeping the body under the 1 MB tsvector limit. PostgreSQL accepts it, so the
    # RunSQL fallback was not needed. pg_trgm must exist before the gin_trgm_ops index.
    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=1024, unique=True)),
                ("note_id", models.TextField(blank=True, db_index=True, null=True)),
                ("type", models.TextField(db_index=True)),
                ("title", models.CharField(max_length=512)),
                ("status", models.TextField(blank=True, db_index=True, null=True)),
                ("priority", models.TextField(blank=True, null=True)),
                ("project", models.TextField(blank=True, db_index=True, null=True)),
                ("due", models.DateField(blank=True, db_index=True, null=True)),
                ("created", models.DateField(blank=True, null=True)),
                ("frontmatter", models.JSONField(default=dict)),
                ("body", models.TextField(blank=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("file_mtime", models.DateTimeField()),
                ("file_size", models.PositiveBigIntegerField()),
                ("parse_error", models.TextField(blank=True, null=True)),
                (
                    "search_vector",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.contrib.postgres.search.SearchVector(
                            "title",
                            django.db.models.functions.text.Left("body", 100000),
                            django.db.models.functions.text.Replace(
                                "path", models.Value("/"), models.Value(" ")
                            ),
                            config="simple",
                        ),
                        output_field=django.contrib.postgres.search.SearchVectorField(),
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="notes", to="vault.tag")),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_title", models.TextField(db_index=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="vault.note",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target_title"), name="link_source_target"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="note",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="note_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="note_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
