# Generated by Django 5.2.17 on 2026-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reread_next",
            field=models.BooleanField(default=True),
        ),
    ]
