# Generated by Django 5.2.17 on 2026-10-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault", "0002_note_reread_next"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("finished_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField()),
                ("summary", models.JSONField(default=dict)),
            ],
        ),
    ]
