# Generated by Django 5.2.17 on 2026-10-06 11:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vault", "0003_index_pass"),
    ]

    # Django cannot alter a generated column's expression in place: drop the GIN index and the
    # column, then add the column back (PostgreSQL recomputes every row) and the index.
    operations = [
        migrations.RemoveIndex(model_name="note", name="note_search_vector_gin"),
        migrations.RemoveField(model_name="note", name="search_vector"),
        migrations.AddField(
            model_name="note",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.SearchVector(
                    django.db.models.functions.text.Replace(
                        "title", models.Value("/"), models.Value(" ")
                    ),
                    django.db.models.functions.text.Replace(
                        django.db.models.functions.text.Left("body", 100000),
                        models.Value("/"),
                        models.Value(" "),
                    ),
                    django.db.models.functions.text.Replace(
                        "path", models.Value("/"), models.Value(" ")
                    ),
                    config="simple",
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="note_search_vector_gin"
            ),
        ),
    ]
